import BannerSection from "@/components/BannerSection";
import Instructors from "@/components/Instructors";
import LearningTips from "@/components/LearningTips";
import TopRatedCourses from "@/components/TopRatedCourses";
import TrendingSection from "@/components/TrendingSection";
import Image from "next/image";

export const metadata = {
  title: "Home | SkillSphere",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <div>
      {/* <p className="text-5xl">This Is Main Page</p> */}
      <BannerSection></BannerSection>
      <TopRatedCourses></TopRatedCourses>
      <TrendingSection></TrendingSection>
      <LearningTips></LearningTips>
      <Instructors></Instructors>
    </div>
  );
}
